import { SKILLS_MASTERY } from '@/components/containers/EmployeeSkillsProfileForm/EmployeeSkillsProfileForm.styles'

export const MASTERY_ARRAY = [
  { id: SKILLS_MASTERY.NOVICE, name: SKILLS_MASTERY.NOVICE },
  { id: SKILLS_MASTERY.ADVANCED, name: SKILLS_MASTERY.ADVANCED },
  { id: SKILLS_MASTERY.COMPETENT, name: SKILLS_MASTERY.COMPETENT },
  { id: SKILLS_MASTERY.PROFICIENT, name: SKILLS_MASTERY.PROFICIENT },
  { id: SKILLS_MASTERY.EXPERT, name: SKILLS_MASTERY.EXPERT }
]
